// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAttack.h"

UFGAttack::UFGAttack(){ }
//void UFGAttack::PerformAttack( TScriptInterface< IFGAggroTargetInterface >	aggroTarget,  AFGEnemy* sourceActor ){ }
