// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableRailroadStation.h"

void AFGBuildableRailroadStation::GetLifetimeReplicatedProps( TArray< FLifetimeProperty >& OutLifetimeProps ) const{ }
void AFGBuildableRailroadStation::BeginPlay(){ }
void AFGBuildableRailroadStation::EndPlay( const EEndPlayReason::Type endPlayReason ){ }
void AFGBuildableRailroadStation::SetName( const FText& name ){ }
void AFGBuildableRailroadStation::RegisteredOnTrack_Implementation( const FRailroadTrackPosition& position ){ }
void AFGBuildableRailroadStation::UnregisteredFromTrack_Implementation(){ }
FRailroadTrackPosition AFGBuildableRailroadStation::GetTrackPosition_Implementation() const{ return FRailroadTrackPosition(); }
