// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableGeneratorNuclear.h"

void AFGBuildableGeneratorNuclear::BeginPlay(){ }
void AFGBuildableGeneratorNuclear::LoadFuel(){ }
