// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGRailroadTrackHologram.h"

void AFGRailroadTrackHologram::GetLifetimeReplicatedProps( TArray< FLifetimeProperty >& OutLifetimeProps ) const{ }
AFGRailroadTrackHologram::AFGRailroadTrackHologram(){ }
void AFGRailroadTrackHologram::BeginPlay(){ }
USceneComponent* AFGRailroadTrackHologram::SetupComponent( USceneComponent* attachParent, UActorComponent* componentTemplate, const FName& componentName ){ return nullptr; }
void AFGRailroadTrackHologram::SetHologramLocationAndRotation( const FHitResult& hitResult ){ }
bool AFGRailroadTrackHologram::MultiStepPlacement(){ return bool(); }
TArray< FItemAmount > AFGRailroadTrackHologram::GetCost( bool includeChildren ) const{ return TArray<FItemAmount>(); }
void AFGRailroadTrackHologram::ConfigureActor(  AFGBuildable* inBuildable ) const{ }
void AFGRailroadTrackHologram::ConfigureComponents(  AFGBuildable* inBuildable ) const{ }
void AFGRailroadTrackHologram::SetMaterial(  UMaterialInterface* material ){ }
void AFGRailroadTrackHologram::CheckValidFloor(){ }
void AFGRailroadTrackHologram::CheckClearance(){ }
void AFGRailroadTrackHologram::OnRep_SplineData(){ }
UFGRailroadTrackConnectionComponent* AFGRailroadTrackHologram::FindOverlappingConnectionComponent( const FVector& location, float radius,  UFGRailroadTrackConnectionComponent* ignoredConnection, bool ignoreIsConnected ) const{ return nullptr; }
