// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGItemDescriptorNuclearFuel.h"

TSubclassOf< UFGItemDescriptor > UFGItemDescriptorNuclearFuel::GetSpentFuelClass( TSubclassOf< UFGItemDescriptorNuclearFuel > inClass ){ return TSubclassOf<UFGItemDescriptor>(); }
