// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGGameUI.h"

void UFGGameUI::PopAllWidgets_Implementation(){ }
void UFGGameUI::NativeTick( const FGeometry& MyGeometry, float InDeltaTime ){ }
//UFGPopupWidget* UFGGameUI::AddCheatWidget( FPopupData popupData ){ return nullptr; }
//void UFGGameUI::HandleFocusLost(){ }
void UFGGameUI::RemoveInteractWidget( UFGInteractWidget* widgetToRemove ){ }
void UFGGameUI::AddInteractWidget_Implementation(UFGInteractWidget* widgetToAdd){ }
void UFGGameUI::HandlePendingMessages_Implementation(){ }
bool UFGGameUI::CanReceiveMessage_Implementation( TSubclassOf<  UFGMessageBase > inMessage ){ return bool(); }
void UFGGameUI::CancelPressed(){ }
void UFGGameUI::RemoveAudioMessage_Implementation(){ }
AFGCharacterPlayer* UFGGameUI::GetFGCharacter(){ return nullptr; }
//void UFGGameUI::AddPawnHUD( UUserWidget* newContent ){ }
//void UFGGameUI::RemovePawnHUD(){ }
