// This file has been automatically generated by the Unreal Header Implementation tool

#include "FactoryGameModule.h"
#include "Modules/ModuleManager.h"
#include "Modules/ModuleInterface.h"

void FFactoryGameModule::StartupModule(){ }
void FFactoryGameModule::ShutdownModule(){ }
