// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableStandaloneSign.h"

AFGBuildableStandaloneSign::AFGBuildableStandaloneSign(){ }
void AFGBuildableStandaloneSign::GetLifetimeReplicatedProps( TArray<FLifetimeProperty>& OutLifetimeProps ) const{ }
void AFGBuildableStandaloneSign::BeginPlay(){ }
void AFGBuildableStandaloneSign::EndPlay( const EEndPlayReason::Type EndPlayReason ){ }
void AFGBuildableStandaloneSign::GainedSignificance_Implementation(){ }
void AFGBuildableStandaloneSign::LostSignificance_Implementation(){ }
void AFGBuildableStandaloneSign::SetSignData( FStandaloneSignData signData, bool bUpdate ){ }
void AFGBuildableStandaloneSign::UpdateSignElements(){ }
void AFGBuildableStandaloneSign::UpdateBackgroundMaterial(){ }
void AFGBuildableStandaloneSign::UpdateSignText(){ }
const FStandaloneSignData& AFGBuildableStandaloneSign::GetSignData(){ return *(new FStandaloneSignData); }
float AFGBuildableStandaloneSign::GetCurrentNormalizedTextScale( ){ return float(); }
float AFGBuildableStandaloneSign::GetCurrentNormalizedTextOffsetZ(){ return float(); }
float AFGBuildableStandaloneSign::GetTextScaleFromNormalizedValue( float value ){ return float(); }
void AFGBuildableStandaloneSign::OnRep_SignData(){ }
