// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGColoredInstanceMeshProxy.h"

UFGColoredInstanceMeshProxy::UFGColoredInstanceMeshProxy(){ }
void UFGColoredInstanceMeshProxy::SetColorSlot( uint8 colorSlotIndex ){ }
void UFGColoredInstanceMeshProxy::BeginPlay(){ }
void UFGColoredInstanceMeshProxy::instantiateInternal(){ }
void UFGColoredInstanceMeshProxy::SetInstanced( bool setToInstanced ){ }
void UFGColoredInstanceMeshProxy::CreateRenderState_Concurrent(){ }
void UFGColoredInstanceMeshProxy::OnHiddenInGameChanged(){ }
