// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGInventoryComponentTrash.h"

void UFGInventoryComponentTrash::OnItemsAdded( int32 idx, int32 num ){ }
