// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPlayerControllerBase.h"

AFGPlayerControllerBase::AFGPlayerControllerBase(){ }
void AFGPlayerControllerBase::BeginPlay(){ }
void AFGPlayerControllerBase::Destroyed(){ }
void AFGPlayerControllerBase::ClientRestart_Implementation( APawn* newPawn ){ }
void AFGPlayerControllerBase::SetIsUsingGamepad( bool newIsUsingGamepad ){ }
void AFGPlayerControllerBase::OnControlledCharacterDied(  AFGCharacterBase* character ){ }
void AFGPlayerControllerBase::OnControlledCharacterRevived(  AFGCharacterBase* character ){ }
void AFGPlayerControllerBase::FlushPressedKeys(){ }
bool AFGPlayerControllerBase::RebindActionKey( FFGKeyMapping newKeyMapping ){ return bool(); }
void AFGPlayerControllerBase::ResetInputBindings(){ }
void AFGPlayerControllerBase::UpdatePlayerInput(){ }
void AFGPlayerControllerBase::SetMouseSensitivity( float newSense ){ }
float AFGPlayerControllerBase::GetMouseSensitivity(){ return float(); }
float AFGPlayerControllerBase::GetDefaultMouseSensitivity(){ return float(); }
FText AFGPlayerControllerBase::GetKeyNameForAction( FName inAction, bool getGamepadKey ){ return FText(); }
FString AFGPlayerControllerBase::GetPresenceString_Implementation() const{ return FString(); }
void AFGPlayerControllerBase::Client_UpdateCappedBandwidth_Implementation(int32 cap){ }
void AFGPlayerControllerBase::Server_UpdateCappedBandwidth_Implementation(int32 cap){ }
bool AFGPlayerControllerBase::Server_UpdateCappedBandwidth_Validate(int32 cap){ return bool(); }
void AFGPlayerControllerBase::SetPresenceEnabled( bool enabled ){ }
void AFGPlayerControllerBase::SetSessionEnabled( bool enabled ){ }
void AFGPlayerControllerBase::DiscardInput(){ }
void AFGPlayerControllerBase::EnablePlayerInput( bool enable ){ }
void AFGPlayerControllerBase::InitDeathInput(){ }
