// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPopupWidgetContent.h"

//bool UFGPopupWidgetContent::GetShouldOkayBeEnabled(){ return bool(); }
//void UFGPopupWidgetContent::SetInstigatorAndInitialize( UObject* instigator ){ }
//void UFGPopupWidgetContent::SetOptionalTextElements( const FText& title, const FText& desc ){ }
//void UFGPopupWidgetContent::NotifyPopupConfirmed(){ }
//void UFGPopupWidgetContent::NotifyPopupCanceled(){ }
