// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSignificanceInterface.h"

//void IFGSignificanceInterface::LostSignificance()
//{
//}

float IFGSignificanceInterface::GetSignificanceBias()
{
	return 0.0f;
}

float IFGSignificanceInterface::GetSignificanceRange()
{
	return 0.0f;
}
